version: '3'

services:
  mongo:
    image: mongo
    restart: always
    expose:
      - '27017'
    volumes:
      - 'data-volume:/data/db'
    networks:
      - app

  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - MONGO_DB=mongodb://mongo:27017
      - NODE_ENV=production
    networks:
      - app

volumes:
  data-volume:

networks:
  app:
    external: false
