version: '3'

services:
  mongo:
    ports:
      - '27017:27017'
  app:
    entrypoint: yarn server:watch
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/home/appuser/app/server:ro
